### ISSUE TITLE
poppy.Instrument filter loading needs refactoring

### ISSUE THREAD

**Issue by josePhoenix** [mperrin/poppy#26]
There's some blurring of lines between WebbPSF and POPPY in the filter code in `poppy.Instrument`. In particular, there are references to a `self._filter_files` attribute (that's populated by JWInstrument) within poppy.Instrument. Also, there are special cases for Webb instruments in `_getWeights` (#20). Refactoring here would be a good opportunity to fix mperrin/webbpsf#28 as well.

**Comment by mperrin** [comment]
Is there still more work on this needed at this point? I know you did some refactoring of this for the WFIRST work already.

**Comment by mperrin** [comment]
Aha, yes, there is still more work needed for this. I see that the Filter named tuple is defined in webbpsf_core rather than in poppy. And the old fallback-if-no-pysynphot code path in poppy was breaking because it doesn't know about Filter named tuples. 

At this point for the current release we don't have time for a whole scale refactoring of this, so I'm just going to do the minimal changes to poppy to unbreak the no-pysynphot case so it might work on Travis.

**Comment by mperrin** [comment]
is this still a live issue? I think you have addressed it in some of your work on the refactoring for the WFIRST stuff?

**Comment by josePhoenix** [comment]
Alas, I think the Filter tuple is still in the wrong project. I'll dig into this today.

**Comment by mperrin** [comment]
Let's push this to the next release - it's not critical and I don't want to add in any unnecessary changes in a rush right before this release.

**Comment by mperrin** [comment]
@josePhoenix do you think you are likely to work on this in the next month? If not let's delay it to the next milestone 0.5.1. Whichever you prefer is fine with me.

**Comment by josePhoenix** [comment]
Honestly, I have to dig back into this to see what the scope really is. I will aspire to the 0.5 release :)

**Comment by mperrin** [comment]
Shall we punt this to a future release?

**Comment by mperrin** [comment]
This is an issue from almost 2 years ago, and I'm not sure it's still relevant. Is it worth keeping open or can we let it go?

**Comment by josePhoenix** [comment]
I will tell you about my idea on Thursday!
